const  product_category_master = require('./product_category_master')
const  cart = require('./cart')
const  product_variants = require('./product_variants')
const  products = require('./products')
products.belongsTo(product_category_master)
products.hasMany(product_variants)
cart.belongsTo(product_variants)
cart.belongsTo(product_category_master)